### ISSUE TITLE
nothing to commit, working tree clean

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-crawler#109]
a companion to #108 - started to happen too
```
2021-10-04T02:24:17.9678385Z ======================================================================
2021-10-04T02:24:17.9679162Z ERROR: datalad_crawler.pipelines.tests.test_simple_with_archives.test_crawl_autoaddtext(True,)
2021-10-04T02:24:17.9680225Z ----------------------------------------------------------------------
2021-10-04T02:24:17.9680760Z Traceback (most recent call last):
2021-10-04T02:24:17.9682004Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
...
2021-10-04T02:24:17.9706448Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_crawler/pipeline.py", line 270, in xrun_pipeline_steps
2021-10-04T02:24:17.9707541Z     for data_ in data_in_to_loop:
2021-10-04T02:24:17.9708615Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_crawler/nodes/annex.py", line 1312, in _finalize
2021-10-04T02:24:17.9709681Z     self._commit("%s%s" % (', '.join(self._states), stats_str), options=["-a"])
2021-10-04T02:24:17.9710800Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad_crawler/nodes/annex.py", line 884, in _commit
2021-10-04T02:24:17.9711634Z     self.repo.call_git(["commit"] + options)
2021-10-04T02:24:17.9712699Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/dataset/gitrepo.py", line 321, in call_git
2021-10-04T02:24:17.9713448Z     read_only=read_only)
2021-10-04T02:24:17.9714448Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/dataset/gitrepo.py", line 262, in _call_git
2021-10-04T02:24:17.9715168Z     env=env)
2021-10-04T02:24:17.9716056Z   File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/cmd.py", line 172, in run
2021-10-04T02:24:17.9716720Z     **results,
2021-10-04T02:24:17.9718361Z datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none commit -a -m '[DATALAD] a commit'' failed with exitcode 1 under /tmp/datalad_temp_check_crawl_autoaddtexthm7uafew [out: 'On branch master
2021-10-04T02:24:17.9719942Z nothing to commit, working tree clean']
```

WTF info
```
2021-10-04T02:22:19.5072864Z ## dependencies
2021-10-04T02:22:19.5073668Z   - annexremote: 1.5.0
2021-10-04T02:22:19.5074495Z   - appdirs: 1.4.4
2021-10-04T02:22:19.5075253Z   - boto: 2.49.0
2021-10-04T02:22:19.5076004Z   - cmd:7z: 16.02
2021-10-04T02:22:19.5076927Z   - cmd:annex: 8.20210903+git115-g0d664d0d3-1~ndall+1
2021-10-04T02:22:19.5077842Z   - cmd:bundled-git: 2.24.0
2021-10-04T02:22:19.5079799Z   - cmd:git: 2.24.0
2021-10-04T02:22:19.5083394Z   - cmd:system-git: 2.33.0
2021-10-04T02:22:19.5083962Z   - cmd:system-ssh: 8.2p1
2021-10-04T02:22:19.5084459Z   - humanize: 3.11.0
2021-10-04T02:22:19.5084957Z   - iso8601: 0.1.16
2021-10-04T02:22:19.5085430Z   - keyring: 23.2.1
2021-10-04T02:22:19.5085919Z   - keyrings.alt: 4.1.0
2021-10-04T02:22:19.5086416Z   - msgpack: 1.0.2
2021-10-04T02:22:19.5086883Z   - requests: 2.26.0
2021-10-04T02:22:19.5087359Z   - scrapy: 2.5.0
2021-10-04T02:22:19.5087812Z   - wrapt: 1.12.1
```

**Comment by yarikoptic** [comment]
seems to be a bug in git-annex (likely that left over print statement fix), resolved by using 8.20210903+git120-gdb55bec8b
